#!/usr/bin/env bash
# on mac: /bin/bash
# name this file pre-push
# and place it in .git/hooks

function check-for-uncommitted-changes {
    git status | grep 'nothing to commit, working tree clean' || { echo "you have uncommitted changes"; exit 1; };
}

function fe-neon {
    cd `git rev-parse --show-top`
    cd ./neon-core

    npm run lint
    if [ $? != 0 ]; then
        echo "push failed due to linter issues..."
        exit 1
    fi

    npm run format-check
    if [ $? != 0 ]; then
        echo "push failed due to format issues..."
        exit 1
    fi
}

check-for-uncommitted-changes
fe-neon &
J1=$!

wait $J1